# https://taskfile.dev
version: "3"
tasks:
  hi: echo ssops

  install-tools:
    cmds:
      - |
        sudo apt install jq tree
        # netstat
        sudo apt install net-tools

  install-docker:
    cmds:
      - |
        sudo apt  install docker.io  # version 24.0.5-0ubuntu1~20.04.1

  ## asdf https://asdf-vm.com/guide/getting-started.html
  asdf-dep: apt install curl git
  asdf-clone:
    cmds:
      - |
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
        cd ~/.asdf && git switch -c bv0.13.1
  asdf-conf:
    cmds:
      - |
        echo <<-Doc > ~/.bashrc
        # Config asdf https://asdf-vm.com/guide/getting-started.html
        . "$HOME/.asdf/asdf.sh"
        . "$HOME/.asdf/completions/asdf.bash"
        Doc
  ## asdf plugins
  setup-nodejs:
    deps:
      - asdf-nodejs-dep
      - asdf-add-nodejs
      - ls-node

  asdf-nodejs-dep:
    cmds:
      - |
        apt-get install dirmngr gpg curl gawk
  asdf-add-nodejs:
    cmds:
      - |
        asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git

  ls-node: asdf list all nodejs
  ## setup
  ln-aliases: ln -s ~/ssops/bash/dot.bash_aliases ~/.bash_aliases
