# https://taskfile.dev
version: "3"
tasks:
  hi: echo ssops

  ## asdf https://asdf-vm.com/guide/getting-started.html
  asdf-dep: apt install curl git
  asdf-clone: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
  asdf-conf:
    cmds:
      - |
        echo <<-Doc > ~/.bashrc
        # Config asdf https://asdf-vm.com/guide/getting-started.html
        . "$HOME/.asdf/asdf.sh"
        . "$HOME/.asdf/completions/asdf.bash"
        Doc
  ## asdf plugins
  asdf-nodejs-dep:
    cmds:
      - |
        apt-get install dirmngr gpg curl gawk
  asdf-nodejs: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  ls-node: asdf list all nodejs

  ## setup
  ln-aliases: ln -s ~/ssops/bash/dot.bash_aliases ~/.bash_aliases
